### ISSUE TITLE
Build Errors in Visual Studio 2017

### ISSUE THREAD

**Issue by kafakiran** [OpenWaterAnalytics/EPANET#388]
After https://github.com/OpenWaterAnalytics/EPANET/pull/384, visual studio 2017 began generating errors without building epanet2.dll file.

There are 114 errors having a description "unresolved external symbol xxx" with codes LNK2001 and LNK1120. The files in the error list are epanet2.exp and epanet2.dll.

I am trying the procedure defined in @Mariosmsk video https://www.youtube.com/watch?v=5Cez_mzG0dM which describes installing Visual Studio 2017 Community with "Desktop Development with C++" option and then opening the source files from "open folder" menu followed by clicking "Build All" under Cmake menu.

It worked fine until the above commit.

Any help will be appreciated.

Thanks.

**Comment by michaeltryby** [comment]
@LRossman I updated my Visual Studio setup, loaded the epanet folder, and used VS cmake integration to generate the build system and build the library. I was able to generate the compiler warnings and errors that @kafakiran experienced. 

Looking over the errors and warnings I think the problem is related to the `.def` file. I've attached the build log so you can have a look. 
   
[buildlog.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2851826/buildlog.txt)

**Comment by LRossman** [comment]
I fixed the VS cmake integration issue. Just add the following `set_source_files` line to the `CMakeLists.txt` file
```
  # the shared library
  if(NOT WIN32)
    add_library(epanet2 SHARED ${EPANET_LIB_ALL})
  else(NOT WIN32)
    add_library(epanet2 SHARED ${EPANET_LIB_ALL} ${PROJECT_SOURCE_DIR}/include/epanet2.def)
    set_source_files_properties(${PROJECT_SOURCE_DIR}/include/epanet2.def PROPERTIES_HEADER_FILE_ONLY TRUE)
  endif(NOT WIN32)
```
Tested both in VS w/cmake and with the command line cmake/msbuild. The resulting DLL works with the existing EPANET 2.0.12 UI. I will push a commit with the fix shortly.

**Comment by kafakiran** [comment]
Still having the same issues on Visual Studio CMake however win_build Makefile.bat works OK with Visual Studio command prompt, so the problem is solved for me. 
Thanks @LRossman.

**Comment by LRossman** [comment]
Just for the record, I once again ran Visual Studio 2017 CMake on the current `dev `branch version downloaded from the OWA GitHub site without having any problems. Here are the steps I used:

1. Downloaded a zipped version of `dev`.
2. Extracted the `EPANET-dev` folder to a new directory.
3. Opened Visual Studio 2017.
4. Clicked the _Open Folder_ link on the Start Page and then selected the `EPANET-dev` folder.
5. Selected the _x86-Release_ configuration from the dropdown box on the toolbar.
6. Selected _CMake | Build All_ from the main menu.
7. Ran `net1.inp` successfully using the executables created in the `User\...\Local\CMakeBuild\...\build\x86-Release\bin\Release` folder.
