### ISSUE TITLE
Pumps with contant power and controls gives wrong results

### ISSUE THREAD

**Issue by allenmlowe** [OpenWaterAnalytics/EPANET#528]
Attached are files to show the problem.

Pump is supposed to to be opened at 10:17:13 but the flow is still 0.
 
![Constant Pump](https://user-images.githubusercontent.com/39788972/64392456-7098d900-d07f-11e9-94af-bb940f281ca9.png)

**Comment by allenmlowe** [comment]
[constant_pump.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3581715/constant_pump.zip)

**Comment by LRossman** [comment]
Thanks @allenmlowe for submitting this issue. There is a bug in the way that v2.2 handles fixed energy pumps (like you have in your example). After fixing the bug, v2.2 gave the same results as v2.0.012, which is still not correct as shown in the figure below:
![image](https://user-images.githubusercontent.com/12769926/65331591-145bac00-db8b-11e9-972e-1552c96c8267.png)

The problem is that using only the v2.0.012 convergence criterion the computed solution gives a very large error in satisfying the fixed energy head equation for the pump. After including the new v2.2 convergence option that the head error be less than 0.1 m, the correct solution was obtained with v2.2 as shown below:
![image](https://user-images.githubusercontent.com/12769926/65332442-b9c34f80-db8c-11e9-8970-f49fc6848447.png)

A PR with the pump bug fix will be forthcoming.

**Comment by allenmlowe** [comment]
Thank you @LRossman and all the programmers who give their time in producing this great program. However not all of us are programmers but for us to be able to help in the development we can still test the program if the toolkit binary file (epanet2.dll) is available as a direct plug-in to the Epanet GUI. Can you release the binary so we can test it.

**Comment by LRossman** [comment]
Version 2.2 is currently undergoing a limited beta test which is being managed by US EPA. You can contact Rob Janke at Janke.Robert@epa.gov to ask to be a reviewer.

**Comment by allenmlowe** [comment]
[Constant Pump time controls.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3704638/Constant.Pump.time.controls.zip)
I would like to submit these two files for testing the pumps for time, simple and rule based controls

**Comment by LRossman** [comment]
The bug referred to in this issue has been fixed via PR #536.

**Comment by allenmlowe** [comment]
Thank you Lew.  Using the latest [pre-release V2.2 0 Beta 2](https://github.com/USEPA/epanet-solver/releases)  I still don't get the desired results. Can you please check with your latest.
[constant_pump_rule-based.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3927124/constant_pump_rule-based.zip)

**Comment by LRossman** [comment]
@allenmlowe I see the problem with your latest example (which also occurs under v2.0) -- the constant HP power pump doesn't produce any flow after it is re-opened at hour 4. This behavior appears to be due to the particular shape of a constant HP pump curve which becomes more vertical (infinite head gradient) as flow approaches 0. (Replacing the constant HP curve with one of the conventional curves included in your example produced a correct solution.) I fixed the code to address this issue by re-setting flow in a constant HP pump to its initial value whenever a control changes its status from closed to open. After that your example ran with no warnings and produced the following results which appear to be correct:

![image](https://user-images.githubusercontent.com/12769926/70242165-5b931b00-173e-11ea-8fb9-4af80ff4b5e8.png)
 
Thanks for developing a simple example that illustrated this behavior.
